suppressPackageStartupMessages(
  suppressWarnings({
    library(DBI)
    library(tidyverse)
    library(rvest)
    library(blastula)
    library(glue)
    library(reticulate)
    library(tidytext)
    library(praise)
  })
)